services:
    redis:
        image: redis:7
        container_name: notification-redis
        ports:
            - "6380:6379"

    postgres:
        image: postgres:17
        container_name: notification-postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: notification_service
        ports: 
            - "5440:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
